import type { Metadata } from "next";
import { Poppins,VT323  } from "next/font/google";
import "./globals.css";


// const poppins = Poppins({
//   weight: ["700"],
//   variable: "--font-poppins", 
// });

const vt323 = VT323({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-vt323",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vt323.className} antialiased bg-neutral-900 text-neutral-100`}
      >
        {children}
      </body>
    </html>
  );
}
